### PR TITLE
MPI IO feature tests

### PR DESCRIPTION
**Pull request by denisbertini**
This vagrant file definition adds the necessary openMPI software stack for reproducable  MPI I/O features test

### CODE REVIEW

**Comment by gabrieleiannetti** [comment]
Hi Denis,

thanks for adding that feature to test MPIIO on Lustre!

I would suggest the following to improve the readability and increase code quality.

The `install_mpi_client` section is doing a lot of different steps. 

It would be good to split the thematic sections of `install_mpi_client`
into separate sections based on what they do e.g.

* `install_mpi_client_packages`
* `build_pmix`
* `build_openmpi`
* `build_epoch`

Also it would be good practice to use a build script within the epoch project itself,
rather than writing down all single steps in the provisioning. 
This also will reduce duplicate code to build the program, which can diverge from required steps on updated project.

Best
Gabriele

**Comment by denisbertini** [comment]
You are right i will do the modifications you proposed.

**Comment by denisbertini** [comment]
For the `epoch` code you meant to add a section like ...
- `build_epoch`
or something else ?
I asked because i plan to add more than these codes to the VM-Client and it would be good to define now
 how to do this properly

**Comment by gabrieleiannetti** [comment]
We should define conventions for defining sections probably e.g.

* Create files on the target e.g. repo files: `create_...`
* Install packages: `install_...`
* Build software from source: `build_...`
* Configure installation parts e.g. creating config files etc.: `configure_...`

You can also check the existing `Vagrant` file where I tried to be consistent and used such conventions for the sections (script functions).

Later I can put sections which belong together into the config management system.  
Therefore it would be good to have a structure which makes it easy to transfer that stuff into the config management...

**Comment by denisbertini** [comment]
ok i got it

**Comment by denisbertini** [comment]
adding multiple step in MPI soft stack provisioning.

**Comment by gabrieleiannetti** [comment]
Hi Denis,  

I got following errors running up the client e.g. `./start_client.sh`:   

```
    client: configure: error: Lustre support requested but not found.  Aborting                                               
    client: make: *** No targets specified and no makefile found.  Stop.                                                      
    client: make: *** No rule to make target `install'.  Stop. 
    
    


    client: make[1]: mpif90: Command not found                                                                                
    client: make[2]: Entering directory `/usr/local/epoch/SDF/FORTRAN'                                                        
    client: mkdir -p obj                                                                                                      
    client: mpif90 -I/usr/include -Iinclude -Iobj -Jinclude -o obj/MPI_CHECK src/mpi_version.f90                              
    client: make[2]: mpif90: Command not found                                                                                
    client: make[2]: Leaving directory `/usr/local/epoch/SDF/FORTRAN'                                                         
    client: make[2]: *** [MPI_CHECK] Error 127                                                                                
    client: make[1]: Leaving directory `/usr/local/epoch/epoch1d'                                                             
    client: make[1]: *** [../SDF/FORTRAN/include/sdf.mod] Error 2                                                             
    client: make[1]: *** Waiting for unfinished jobs....                                                                      
    client: make[1]: *** [random_generator.o] Error 127                                                                       
    client: make: *** [commit] Error 2                                                                                        
    client: cp: cannot stat ‘bin/epoch1d’: No such file or directory 
```

You should always destroy the VM in that case the client with `vagrant destroy client` to test your installation on a clean installed VM :-).

Best
Gabriele

**Comment by denisbertini** [comment]
It should be now repaired, installing correct lustre-client module

**Pull request merged**
